/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package activofijos;

import ClaseConectar.Conectar;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jaime Gattorno
 */
public class Asignaciones extends java.awt.Dialog {

    String cadena = "";
    /**
     * Creates new form Asignaciones
     */
    public Asignaciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jComboBoxcodigoubicacionIniciar("");
        jComboBoxcodigoestadoIniciar("");
        jComboBoxcodigoproveedoresIniciar("");
        jComboBoxcodigoclaseIniciar("");
        jComboBoxcodigousuarioIniciar("");
        establecerAcceso(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextcodigoactivo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextcodigovogue = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextmarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextmodelo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxcodigoclase = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxcodigoubicacion = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxcodigoresponsable = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxcodigoestado = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextdiscoduro = new javax.swing.JTextField();
        jTextip = new javax.swing.JTextField();
        jTextmac = new javax.swing.JTextField();
        jTextmenoriaram = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jComboBoxcodigoproveedores = new javax.swing.JComboBox();
        jTextmonto = new javax.swing.JTextField();
        jTextfechagarantia = new javax.swing.JTextField();
        jTextcodigoempleado = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextserie = new javax.swing.JTextField();
        jTextcolor = new javax.swing.JTextField();
        jTextdescripcion = new javax.swing.JTextField();
        jTextfechainventario = new javax.swing.JTextField();
        jTextfecha1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextprocesador = new javax.swing.JTextField();
        jTextso = new javax.swing.JTextField();
        jTextversion = new javax.swing.JTextField();
        jTextarquitectura = new javax.swing.JTextField();
        bntGuardar = new javax.swing.JButton();
        bntEliminar = new javax.swing.JButton();
        bntBuscar = new javax.swing.JButton();
        bntImprimir = new javax.swing.JButton();
        bntRegresar = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextnumerofactura = new javax.swing.JTextField();
        jTextcheque = new javax.swing.JTextField();
        jTextcajachica = new javax.swing.JTextField();
        bntNuevo = new javax.swing.JButton();
        lblfoto = new javax.swing.JLabel();
        jButtonFoto = new javax.swing.JButton();
        jTextFoto = new javax.swing.JTextField();
        bntModificar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(900, 630));
        setPreferredSize(new java.awt.Dimension(958, 670));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ASIGNACION DE ACTIVOS");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 24));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 550, 20));

        jLabel2.setText("No.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        jTextcodigoactivo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextcodigoactivo.setDoubleBuffered(true);
        add(jTextcodigoactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 129, -1));

        jLabel3.setText("Codigo Vogue");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 83, 20));
        add(jTextcodigovogue, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 129, -1));

        jLabel4.setText("Marca");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 91, 20));
        add(jTextmarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 129, -1));

        jLabel5.setText("Modelo");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));
        add(jTextmodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 129, -1));

        jLabel7.setText("Clase");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 73, -1));

        jComboBoxcodigoclase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxcodigoclaseActionPerformed(evt);
            }
        });
        add(jComboBoxcodigoclase, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 290, -1));

        jLabel8.setText("Ubicacion");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 73, -1));

        jComboBoxcodigoubicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxcodigoubicacionActionPerformed(evt);
            }
        });
        add(jComboBoxcodigoubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 290, -1));

        jLabel9.setText("Responsable");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 91, -1));

        add(jComboBoxcodigoresponsable, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 290, -1));

        jLabel10.setText("Estado");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 73, -1));

        add(jComboBoxcodigoestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 290, -1));

        jLabel22.setText("Memoria Ram:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel21.setText("Mac:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jLabel20.setText("IP   :");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 40, -1));

        jLabel19.setText("Disco Duro:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));
        add(jTextdiscoduro, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 129, -1));
        add(jTextip, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 129, -1));
        add(jTextmac, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 129, -1));
        add(jTextmenoriaram, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, 129, 20));

        jLabel29.setText("Proveedor:");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, 20));

        jLabel28.setText("Fecha:");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 80, 20));

        jLabel31.setText("Monto");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 90, 20));

        jLabel30.setText("Fecha Final de la Garantia :");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 140, 20));

        add(jComboBoxcodigoproveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 460, 190, -1));
        add(jTextmonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 130, -1));
        add(jTextfechagarantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 120, -1));
        add(jTextcodigoempleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 110, -1));

        jLabel13.setText("Descripcion");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, 20));

        jLabel14.setText("Fecha de Inventario");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, -1, -1));

        jLabel15.setText("Serie");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        jLabel16.setText("Color");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        jLabel17.setText("Codigo del NOI");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        jTextserie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextserieActionPerformed(evt);
            }
        });
        add(jTextserie, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 160, -1));
        add(jTextcolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 110, -1));
        add(jTextdescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 400, -1));
        add(jTextfechainventario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 160, -1));
        add(jTextfecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 130, -1));

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Detalle de Adquisición");
        jLabel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 380, -1));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText(" LLENAR SI ES CPU");
        jLabel23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 380, -1));

        jLabel24.setText("Procesador:");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        jLabel25.setText("SO:");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        jLabel26.setText("Version:");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        jLabel27.setText("Arquitectura:");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 410, -1, -1));
        add(jTextprocesador, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 320, 150, -1));
        add(jTextso, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 150, -1));
        add(jTextversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 150, -1));
        add(jTextarquitectura, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 150, -1));

        bntGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/activofijos/Iconos/Guardar32.png"))); // NOI18N
        bntGuardar.setToolTipText("guardar");
        bntGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardarActionPerformed(evt);
            }
        });
        add(bntGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 590, 40, 40));

        bntEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/activofijos/Iconos/Borrar32.png"))); // NOI18N
        bntEliminar.setToolTipText("Eliminar");
        add(bntEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, 40, 40));

        bntBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/activofijos/Iconos/Buscar32.png"))); // NOI18N
        bntBuscar.setToolTipText("Buscar");
        bntBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarActionPerformed(evt);
            }
        });
        add(bntBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 40, 40));

        bntImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/activofijos/Iconos/Imprimir32.png"))); // NOI18N
        bntImprimir.setToolTipText("Imprimir");
        bntImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntImprimirActionPerformed(evt);
            }
        });
        add(bntImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, 40, 40));

        bntRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/activofijos/Iconos/regresar32.png"))); // NOI18N
        bntRegresar.setToolTipText("Regresar");
        bntRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegresarActionPerformed(evt);
            }
        });
        add(bntRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 590, 40, 40));

        jLabel33.setText("Factura No.");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, -1, -1));

        jLabel32.setText("Cheque No.");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 520, -1, -1));

        jLabel35.setText("Caja Chica:");
        add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, -1, -1));
        add(jTextnumerofactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 160, -1));
        add(jTextcheque, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 160, -1));
        add(jTextcajachica, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 160, -1));

        bntNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/activofijos/Iconos/Nuevo32.png"))); // NOI18N
        bntNuevo.setToolTipText("Nuevo");
        bntNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNuevoActionPerformed(evt);
            }
        });
        add(bntNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 40, 40));

        lblfoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfoto.setText("FOTO");
        lblfoto.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(lblfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 310, 220));

        jButtonFoto.setText("Cargar Foto");
        jButtonFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFotoActionPerformed(evt);
            }
        });
        add(jButtonFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 340, -1, -1));

        jTextFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFotoActionPerformed(evt);
            }
        });
        add(jTextFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 380, 100, -1));

        bntModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/activofijos/modificar32.png"))); // NOI18N
        bntModificar.setToolTipText("modificar");
        bntModificar.setMaximumSize(new java.awt.Dimension(65, 41));
        bntModificar.setMinimumSize(new java.awt.Dimension(65, 41));
        bntModificar.setPreferredSize(new java.awt.Dimension(65, 41));
        bntModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntModificarActionPerformed(evt);
            }
        });
        add(bntModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 40, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void jComboBoxcodigoclaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxcodigoclaseActionPerformed

    }//GEN-LAST:event_jComboBoxcodigoclaseActionPerformed

    private void jComboBoxcodigoubicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxcodigoubicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxcodigoubicacionActionPerformed

    private void jTextserieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextserieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextserieActionPerformed

    private void bntGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardarActionPerformed
        // TODO add your handling code here:
        String cCodigoActivo = "0";
        Integer.parseInt(cCodigoActivo);
        String cDescripcion = "";
        String cMarca = "";
        String cModelo = "";
        String cSerie = "";
        String cCodigoUbicacion = "0";
        Integer.parseInt(cCodigoUbicacion);
        String cCodigoEstado = "0";
        Integer.parseInt(cCodigoEstado);
        String cCodigoProveedor = "";
        String dFecha = "";
        String nNumerofactura = "";
        double nMonto = 0.0;
        Integer nCheque = 0;
        String cCodigoClase = "0";
        Integer.parseInt(cCodigoClase);
        String cCodigoResponsable = "0";
        Integer.parseInt(cCodigoResponsable);
        String dFechainventario = "";
        String cCodigovogue = "0";
        Integer.parseInt(cCodigovogue);
        Integer cCodigoempleado = 0;
        String dFechagarantia = "";
        String cDiscoduro = "";
        String cFoto = "";
        String cMenoriaram = "";
        String cIp = "";
        String cMac = "";
        String cProcesador = "";
        String cSo = "";
        String cVersion = "";
        String cArquitectura = "";
        String cColor = "";
        String cCajachica = "";
        String cTempo = "";

        cCodigoActivo = jTextcodigoactivo.getText();
        cDescripcion = jTextdescripcion.getText();
        cMarca = jTextmarca.getText();
        cModelo = jTextmodelo.getText();
        cSerie = jTextserie.getText();
        cCodigoUbicacion =  jComboBoxcodigoubicacion.getSelectedItem().toString().substring(0, 7);
        cCodigoEstado = jComboBoxcodigoestado.getSelectedItem().toString().substring(0,7);
        cCodigoProveedor =  jComboBoxcodigoproveedores.getSelectedItem().toString().substring(0, 7);

        // Validar Fecha
        if (jTextfecha1.getText().trim().length() == 0){
            dFecha = "1900/01/01";
        } else {
            dFecha = jTextfecha1.getText();
        }
        // Validar Numero de factura
        if (jTextnumerofactura.getText().trim().length() == 0) {
            nNumerofactura = "";
        } else {
            nNumerofactura = jTextnumerofactura.getText();
        }
        // Validar Monto
        if (jTextmonto.getText().trim().length() == 0){
            nMonto = 0;
        } else {
            nMonto = Double.parseDouble(jTextmonto.getText());
        }
        // Validar Cheque
        if (jTextcheque.getText().trim().length() == 0) {
            nCheque = 0;
        } else {
            nCheque = Integer.parseInt(jTextcheque.getText());
        }

        cCodigoClase = jComboBoxcodigoclase.getSelectedItem().toString().substring(0,7);;
        cCodigoResponsable = jComboBoxcodigoresponsable.getSelectedItem().toString().substring(0, 7);

        // Validar Fecha inventario
        if (jTextfechainventario.getText().trim().length() == 0){
            dFechainventario = "1900/01/01";
        } else {
            dFechainventario = jTextfechainventario.getText();
        }

        cCodigovogue = jTextcodigovogue.getText();

        // Validar Codigo Empleado
        if (jTextcodigoempleado.getText().trim().length() == 0) {
            cCodigoempleado = 0;
        } else {
            cCodigoempleado = Integer.parseInt(jTextcodigoempleado.getText());
        }

        // Validar Fecha Garantia
        if (jTextfechagarantia.getText().trim().length() == 0){
            dFechagarantia = "1900/01/01";
        } else {
            dFechagarantia = jTextfechagarantia.getText();
        }

        cDiscoduro = jTextdiscoduro.getText();
        cFoto = jTextFoto.getText();
        cMenoriaram = jTextmenoriaram.getText();
        cIp = jTextip.getText();
        cMac = jTextmac.getText();
        cProcesador = jTextprocesador.getText();
        cSo = jTextso.getText();
        cVersion = jTextversion.getText();
        cArquitectura = jTextarquitectura.getText();
        cColor = jTextcolor.getText();
        cCajachica = jTextcajachica.getText();

        // Codigo para conectarse y grabar en la base de datos

        Conectar nConexion = new Conectar();
        nConexion.conectar();
        Statement st = nConexion.conexion();

        String cSql;
        cSql = "DELETE FROM activos WHERE codigoactivo = '" + cCodigoActivo + "';" +
            "INSERT INTO activos"+
            "(codigoactivo, descripcion, marca, modelo, serie, codigoubicacion, codigoestado, codigoproveedor,"
            + " fecha, numerofactura, monto, cheque, codigoclase, codigoresponsable, fechainventario, codigovogue,"
            + " codigoempleado, fechagarantia, discoduro, foto, menoriaram, ip, mac, procesador, so,version,"
            + " arquitectura, color, cajachica)" +
            " SELECT " + cCodigoActivo + "" +
            "   ,'" + cDescripcion + "'" +
            "   ,'" + cMarca + "'" +
            "   ,'" + cModelo + "'" +
            "   ,'" + cSerie + "'" +
            "   , " + cCodigoUbicacion + "" +
            "   , " + cCodigoEstado + "" +
            "   , " + cCodigoProveedor + "" +
            "   , '" + dFecha + "'" +
            "   , '" + nNumerofactura + "'"+
            "   , " + nMonto +
            "   , " + nCheque +
            "   , " + cCodigoClase + "" +
            "   , " + cCodigoResponsable + "" +
            "   ,'" + dFechainventario + "'" +
            "   , " + cCodigovogue + "" +
            "   , " + cCodigoempleado + "" +
            "   ,'" + dFechagarantia + "'" +
            "   ,'" + cDiscoduro + "'" +
            "   ,'" + cFoto + "'" +    
            "   ,'" + cMenoriaram + "'" +
            "   ,'" + cIp + "'" +
            "   ,'" + cMac + "'" +
            "   ,'" + cProcesador + "'" +
            "   ,'" + cSo + "'" +
            "   ,'" + cVersion + "'" +
            "   ,'" + cArquitectura + "'" +
            "   ,'" + cColor + "'" +
            "   ,'" + cCajachica + "'" +
            " WHERE NOT EXISTS " +
            "    ( SELECT * FROM activos " +
            "         WHERE codigoactivo = '" + cCodigoActivo + "' )";

        nConexion.slqActualiza(st, cSql);
        nConexion.cerrar(st);
        nConexion.desconectar();
        JOptionPane.showMessageDialog(null, "Los datos se guardaron con éxito");
        
        establecerAcceso(0); //permite la ediciòn de los datos
        
        
    }//GEN-LAST:event_bntGuardarActionPerformed

    private void bntBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarActionPerformed
        Buscar lBuscar = new Buscar(new javax.swing.JDialog(), true);
        String cElegido = "";
        lBuscar.pack();
        lBuscar.setLocationRelativeTo(null);
        lBuscar.setVisible(true);

        cElegido = lBuscar.getjTextElegido();
        
        if (cElegido.length() > 0) {
            Conectar nConexion = new Conectar();
            nConexion.conectar();
            Statement st = nConexion.conexion();
            
            String cSql = "";
            String cWhere = "";
            
            cWhere = " WHERE A.codigoactivo = " + cElegido;
            
            cSql = " SELECT " +
                    "coalesce(codigoactivo, 0)\n" +
                    ",coalesce(descripcion, '')\n" +
                    ",coalesce(marca, '')\n" +
                    ",coalesce(modelo, '')\n" +
                    ",coalesce(serie, '')\n" +
                    ",coalesce(codigoubicacion, 0)\n" +
                    ",coalesce(codigoestado, 0)\n" +
                    ",coalesce(codigoproveedor, '')\n" +
                    ",coalesce(fecha::text, '')\n" +
                    ",coalesce(numerofactura, '')\n" +
                    ",coalesce(monto, 0)\n" +
                    ",coalesce(cheque, 0)\n" +
                    ",coalesce(codigofallas, 0)\n" +
                    ",coalesce(codigoclase, 0)\n" +
                    ",coalesce(codigoresponsable, 0)\n" +
                    ",coalesce(fechainventario::text, '')\n" +
                    ",coalesce(codigovogue, 0)\n" +
                    ",coalesce(codigoempleado, 0)\n" +
                    ",coalesce(fechagarantia::text, '')\n" +
                    ",coalesce(discoduro, '')\n" +
                    ",coalesce(menoriaram, '')\n" +
                    ",coalesce(ip, '')\n" +
                    ",coalesce(mac, '')\n" +
                    ",coalesce(procesador, '')\n" +
                    ",coalesce(so, '')\n" +
                    ",coalesce(version, '')\n" +
                    ",coalesce(arquitectura, '')\n" +
                    ",coalesce(color, '')\n" +
                    ",coalesce(cajachica, '')\n" +
                    ",coalesce(foto, '')\n" +
                    " FROM activos A " + cWhere ;
            // JOptionPane.showMessageDialog(null, cSql);
            
            ResultSet rs = nConexion.slqConsulta(st,cSql);
            
            try {
                rs.next();
                jTextcodigoactivo.setText(rs.getObject(1).toString() );
                jTextdescripcion.setText(rs.getObject(2).toString() );
                jTextmarca.setText(rs.getObject(3).toString() );
                jTextmodelo.setText(rs.getObject(4).toString() );
                jTextserie.setText(rs.getObject(5).toString() );
                // jTextcodigoubicacion.setText(rs.getObject(6).toString() );
                // jTextcodigoestado.setText(rs.getObject(7).toString() );
                // jTextcodigoproveedor.setText(rs.getObject(8).toString() );
                 jTextfecha1.setText(rs.getObject(9).toString());
                 jTextnumerofactura.setText(rs.getObject(10).toString() );
                 jTextmonto.setText(rs.getObject(11).toString() );
                 jTextcheque.setText(rs.getObject(12).toString() );
                 //jTextcodigoclase.setText(rs.getObject(14).toString() );
                 //jTextcodigoresponsable.setText(rs.getObject(15).toString() );
                 jTextfechainventario.setText(rs.getObject(16).toString() );
                 jTextcodigovogue.setText(rs.getObject(17).toString() );
                 jTextcodigoempleado.setText(rs.getObject(18).toString() );
                 //jTextfoto.setText(rs.getObject(19).toString() );
                 jTextfechagarantia.setText(rs.getObject(19).toString() );
                 jTextdiscoduro.setText(rs.getObject(20).toString() );
                 jTextmenoriaram.setText(rs.getObject(21).toString() );
                 jTextip.setText(rs.getObject(22).toString() );
                 jTextmac.setText(rs.getObject(23).toString() );
                 jTextprocesador.setText(rs.getObject(24).toString() );
                 jTextso.setText(rs.getObject(25).toString() );
                 jTextversion.setText(rs.getObject(26).toString() );
                 jTextarquitectura.setText(rs.getObject(27).toString() );
                 jTextcolor.setText(rs.getObject(28).toString() );
                 jTextcajachica.setText(rs.getObject(29).toString() );
                 jTextFoto.setText(rs.getObject(30).toString() );
                 
                 /*
                jComboBoxcodigousuarioIniciar();
                 
                */ 
            } catch (SQLException ex) {
                Logger.getLogger(Asignaciones.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                jComboBoxcodigoubicacionIniciar(rs.getObject(6).toString());
                jComboBoxcodigoestadoIniciar(rs.getObject(7).toString());
                jComboBoxcodigoproveedoresIniciar(rs.getObject(8).toString());
                jComboBoxcodigoclaseIniciar(rs.getObject(14).toString());
                jComboBoxcodigousuarioIniciar(rs.getObject(15).toString());
            } catch (SQLException ex) {
                Logger.getLogger(Asignaciones.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            nConexion.cerrar(st);
            nConexion.desconectar();
            
            Image foto = getToolkit().getImage(jTextFoto.getText());
            foto = foto.getScaledInstance(300, 210, Image.SCALE_DEFAULT);
            lblfoto.setIcon(new ImageIcon(foto));  
            
            establecerAcceso(0); //permite la ediciòn de los datos
        }
    }//GEN-LAST:event_bntBuscarActionPerformed

    private void bntImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntImprimirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_bntImprimirActionPerformed

    private void bntRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegresarActionPerformed
        // BOTON DE ASIGNACION
        this.dispose();
    }//GEN-LAST:event_bntRegresarActionPerformed

    private void bntNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNuevoActionPerformed
        jTextcodigoactivo.setText("");
        jTextdescripcion.setText("");
        jTextmarca.setText("");
        jTextmodelo.setText("");
        jTextserie.setText("");
        jTextfecha1.setText("");
        jTextnumerofactura.setText("");
        jTextmonto.setText("");
        jTextcheque.setText("");
        jTextfechainventario.setText("");
        jTextcodigovogue.setText("");
        jTextcodigoempleado.setText("");
        jTextfechagarantia.setText("");
        jTextdiscoduro.setText("");
        jTextFoto.setText("");
        jTextmenoriaram.setText("");
        jTextip.setText("");
        jTextmac.setText("");
        jTextprocesador.setText("");
        jTextso.setText("");
        jTextversion.setText("");
        jTextarquitectura.setText("");
        jTextcolor.setText("");
        jTextcajachica.setText("");        
                   
              
        jComboBoxcodigoubicacionIniciar("");
        jComboBoxcodigoestadoIniciar("");
        jComboBoxcodigoproveedoresIniciar("");
        jComboBoxcodigoclaseIniciar("");
        //jComboBoxcodigoresponsableIniciar("");
        jComboBoxcodigousuarioIniciar("");
        establecerAcceso(1);

        try {
            jTextcodigoactivo.setText(devolverCodigo().toString());
        } catch (SQLException ex) {
            Logger.getLogger(Asignaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextcodigovogue.setFocusable(true);
        
            Image foto = getToolkit().getImage(jTextFoto.getText());
            foto = foto.getScaledInstance(300, 210, Image.SCALE_DEFAULT);
            lblfoto.setIcon(new ImageIcon(foto));
        
    }//GEN-LAST:event_bntNuevoActionPerformed

    private void jButtonFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFotoActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filtro = new FileNameExtensionFilter ("Formatos de Archivos JPEG(*.JPG;*.JPEG)","JPG","JPEG");
        JFileChooser archivo = new JFileChooser();
        archivo.addChoosableFileFilter(filtro);
        archivo.setDialogTitle("Abrir Archivo");
        File ruta = new File ("C:\\NetBeansProjects\\ActivosFijos 0.0.0.7\\Fotos");
        archivo.setCurrentDirectory(ruta);
        int ventana = archivo.showOpenDialog(null);
        if(ventana == JFileChooser.APPROVE_OPTION);
        {
            File file = archivo.getSelectedFile();
            jTextFoto.setText(String.valueOf(file));
            Image foto = getToolkit().getImage(jTextFoto.getText());
            foto = foto.getScaledInstance(300, 210, Image.SCALE_DEFAULT);
            lblfoto.setIcon(new ImageIcon(foto));          
            
        } 
    }//GEN-LAST:event_jButtonFotoActionPerformed

    private void jTextFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFotoActionPerformed

    private void bntModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntModificarActionPerformed
        // TODO add your handling code here:
        // Permitir combos
        // Accesos
        {
            String cCodigoUbicacion =  jComboBoxcodigoubicacion.getSelectedItem().toString().substring(0, 7);
            String cCodigoEstado = jComboBoxcodigoestado.getSelectedItem().toString().substring(0,7);
            String cCodigoProveedor =  jComboBoxcodigoproveedores.getSelectedItem().toString().substring(0, 8);
            String cCodigoClase = jComboBoxcodigoclase.getSelectedItem().toString().substring(0,7);;
            String cCodigoResponsable = jComboBoxcodigoresponsable.getSelectedItem().toString().substring(0, 7);
            jComboBoxcodigoubicacionIniciar(cCodigoUbicacion);
            jComboBoxcodigoestadoIniciar(cCodigoEstado);
            jComboBoxcodigoproveedoresIniciar(cCodigoProveedor);
            jComboBoxcodigoclaseIniciar(cCodigoClase);
            jComboBoxcodigousuarioIniciar(cCodigoResponsable);

            establecerAcceso(1);//no permite la ediciòn de los datos, Cambiar a 1 para permitir

        }
    }//GEN-LAST:event_bntModificarActionPerformed
    private Integer devolverCodigo() throws SQLException {
        Integer nDevolver = 0;
        String lcSQL = "SELECT max(codigoactivo) codigoactivo FROM activos;";

        Conectar nConexion = new Conectar();
        nConexion.conectar();
        Statement st = nConexion.conexion();
        
        ResultSet rs = nConexion.slqConsulta(st, lcSQL);
        
        rs.next();
        nDevolver = (Integer) rs.getObject(1) ;
        nDevolver++;
        
        nConexion.cerrar(st);
        nConexion.desconectar();

        return nDevolver;
    }
    private void jComboBoxcodigoubicacionIniciar(String pBuscar) {
        // llenar el combo box con los datos requeridos
       jComboBoxcodigoubicacion.removeAllItems();
       
       String cWhere = pBuscar;
       String cWhere1 = pBuscar;
       String cSql;
       if(cWhere.length() > 0){
           cWhere = " WHERE codigoubicacion = " + cWhere + "\n";
           cWhere1 = " WHERE codigoubicacion != " + cWhere1 + "\n";
       }
       
        cSql = "SELECT (codigoubicacion  || Repeat(' ',7) || descripcion) As ubicaciones, '*' AS orden \n" +
                " FROM ubicaciones \n" + 
                cWhere + "UNION \n" +
                "SELECT (codigoubicacion  || Repeat(' ',7) || descripcion) As ubicaciones, '' AS orden \n" +
                " FROM ubicaciones \n" + 
                cWhere1 +
                " ORDER BY 2 DESC, 1 \n" ;
        
        //System.out.println(cSql);
        
        Conectar nConexion = new Conectar();
        nConexion.conectar();
        Statement st = nConexion.conexion();
        ResultSet rs = nConexion.slqConsulta(st, cSql);  // Resultado
       
        String cPrimera = "";
        try {
            while (rs.next()) { 
                if(cPrimera.length() == 0) {
                    cPrimera = rs.getString("ubicaciones");
                    
                }
                
                        
                String cLinea = rs.getString("ubicaciones");
                // aqui recuperamos los valores obtenidos y se los pasamos al jComboBix
                this.jComboBoxcodigoubicacion.addItem(cLinea);
            } // fin de while
        } catch (Exception eEc ){
            // Mostrr el error
            System.out.println("Error Sql " + eEc);
        }
        this.jComboBoxcodigoubicacion.setSelectedItem(cPrimera);
        nConexion.cerrar(st);
        nConexion.desconectar();
    } // fin de JComboBoxcodigoubicacionIniciar()
        
    private void jComboBoxcodigoestadoIniciar(String pBuscar) {
        // llenar el combo box con los datos requeridos
        
        jComboBoxcodigoestado.removeAllItems();
        String cWhere = pBuscar;
        String cWhere1 = pBuscar;
        String cSql;
        if(cWhere.length() > 0){
           cWhere = " WHERE codigoestado = " + cWhere + "\n";
           cWhere1 = " WHERE codigoestado != " + cWhere1 + "\n";
        }
        cSql = "SELECT (codigoestado || Repeat(' ',7) || descripcion) As Estado, '*' As orden \n" +
                "                 FROM estados  \n" +
                cWhere + "UNION \n" +
                "SELECT (codigoestado || Repeat(' ',7) || descripcion) As Estado, '' As orden \n" +
                "                 FROM estados  \n" +
                cWhere1 +
                " ORDER BY 2 DESC, 1  ";
        
        Conectar nConexion = new Conectar();
        nConexion.conectar();
        Statement st = nConexion.conexion();
        ResultSet rs = nConexion.slqConsulta(st, cSql);
   
        try {
            while (rs.next()) {

                String cLinea = rs.getString("Estado");
                // aqui recuperamos los valores obtenidos y se los pasamos al jComboBix
                this.jComboBoxcodigoestado.addItem(cLinea);
            } // fin de while
        } catch (Exception eEc ){
            // Mostrar el error
            System.out.println("Error Sql " + eEc);
        }
        nConexion.cerrar(st);
        nConexion.desconectar();
        
    } // fin de jComboBoxcodigoestadoIniciar()
        
   
    private void jComboBoxcodigoproveedoresIniciar(String pBuscar) {
        // llenar el combo box con los datos requeridos
        
        jComboBoxcodigoproveedores.removeAllItems();
        String cWhere = pBuscar.trim();
        String cWhere1 = pBuscar.trim();
        String cSql;
        if(cWhere.length() > 0){
           cWhere = " WHERE codigoproveedor = '" + cWhere + "' \n";
           cWhere1 = " WHERE codigoproveedor != '" + cWhere1 + "' \n";
        }
        
        cSql = "SELECT (codigoproveedor || Repeat(' ',7) || nombreempresa) As Proveedor, '*' AS Orden \n" +
                " FROM proveedores  \n" +
                cWhere + "UNION \n" +
                "SELECT (codigoproveedor || Repeat(' ',7) || nombreempresa) As Proveedor, '' AS Orden \n" +
                " FROM proveedores  \n" +
                cWhere1 +
                " ORDER BY 2 DESC, 1  ";
        
        //System.out.println(cSql);
        
        Conectar nConexion = new Conectar();
        nConexion.conectar();
        Statement st = nConexion.conexion();
        ResultSet rs = nConexion.slqConsulta(st, cSql);
        
        try {
            while (rs.next()) {

                String cLinea = rs.getString("proveedor");
                // aqui recuperamos los valores obtenidos y se los pasamos al jComboBix
                this.jComboBoxcodigoproveedores.addItem(cLinea);
            } // fin de while
        } catch (Exception eEc ){
            // Mostrr el error
            System.out.println("Error Sql " + eEc);
        }
        nConexion.cerrar(st);
        nConexion.desconectar();
              
    } // fin de jComboBoxcodigoproveedoresIniciar()    
       
    private void jComboBoxcodigoclaseIniciar(String pBuscar) {
        // llenar el combo box con los datos requeridos
        
        jComboBoxcodigoclase.removeAllItems();
        String cWhere = pBuscar;
        String cWhere1 = pBuscar;
        String cSql;
        if(cWhere.length() > 0){
           cWhere = " WHERE codigoclase = " + cWhere + " \n";
           cWhere1 = " WHERE codigoclase != " + cWhere1 + " \n";
        }
        
        cSql = "SELECT (codigoclase || Repeat(' ',7) || descripcion) As clase, '*' AS Orden \n" +
                "                 FROM clases  \n" +
                cWhere + "UNION \n" +
                "SELECT (codigoclase || Repeat(' ',7) || descripcion) As clase, '' AS Orden \n" +
                "                 FROM clases  \n" +
                cWhere1 +
                " ORDER BY 2 DESC, 1  ";
        
        Conectar nConexion = new Conectar();
        nConexion.conectar();
        Statement st = nConexion.conexion();
        ResultSet rs = nConexion.slqConsulta(st, cSql);
        
        try {
            while (rs.next()) {

                String cLinea = rs.getString("clase");
                // aqui recuperamos los valores obtenidos y se los pasamos al jComboBix
                this.jComboBoxcodigoclase.addItem(cLinea);
            } // fin de while
        } catch (Exception eEc ){
            // Mostrr el error
            System.out.println("Error Sql " + eEc);
        }
        nConexion.cerrar(st);
        nConexion.desconectar();
      
    } // fin de jComboBoxcodigoclaseIniciar()
         
    

    private void jComboBoxcodigousuarioIniciar(String pBuscar) {
        // llenar el combo box con los datos requeridos
        
        jComboBoxcodigoresponsable.removeAllItems();
        String cWhere = pBuscar;
        String cWhere1 = pBuscar;
        String cSql;
        if(cWhere.length() > 0){
           cWhere = " WHERE codigoresponsable = " + cWhere + " \n";
           cWhere1 = " WHERE codigoresponsable != " + cWhere1 + " \n";
        }
        
        cSql = "SELECT (codigoresponsable || Repeat(' ',7) || nombre) As Responsable, '*' AS Orden \n" +
            "  FROM responsables  \n" +
            cWhere + "UNION \n" +
            "SELECT (codigoresponsable || Repeat(' ',7) || nombre) As Responsable, '' AS Orden \n" +
            "  FROM responsables  \n" +
            cWhere1 +    
            " ORDER BY 2 DESC, 1  ";    

        Conectar nConexion = new Conectar();
        nConexion.conectar();
        Statement st = nConexion.conexion();
        ResultSet rs = nConexion.slqConsulta(st, cSql);
        
        try {
            while (rs.next()) {

                String cLinea = rs.getString("Responsable");
                // aqui recuperamos los valores obtenidos y se los pasamos al jComboBix
                this.jComboBoxcodigoresponsable.addItem(cLinea);
            } // fin de while
        } catch (Exception eEc ){
            // Mostrr el error
            System.out.println("Error Sql " + eEc);
        }
        nConexion.cerrar(st);
        nConexion.desconectar();
     
        
    } // fin de jComboBoxcodigousuarioIniciar()
    
    private void establecerAcceso(Integer nAcceso){
        Integer lnAcceso = nAcceso;
        
        // Al iniciar el programa 
        if(lnAcceso == 0){
            jComboBoxcodigoclase.setEnabled(false);
            jComboBoxcodigoestado.setEnabled(false);
            jComboBoxcodigoproveedores.setEnabled(false);
            jComboBoxcodigoresponsable.setEnabled(false);
            jComboBoxcodigoubicacion.setEnabled(false);
            jTextarquitectura.setEnabled(false);
            jTextcajachica.setEnabled(false);
            jTextcheque.setEnabled(false);
            jTextcodigoactivo.setEnabled(false);
            jTextcodigoempleado.setEnabled(false);
            jTextcodigovogue.setEnabled(false);
            jTextcolor.setEnabled(false);
            jTextdescripcion.setEnabled(false);
            jTextdiscoduro.setEnabled(false);
            jTextFoto.setEnabled(false);
            jTextfecha1.setEnabled(false);
            jTextfechagarantia.setEnabled(false);
            jTextfechainventario.setEnabled(false);
            jTextip.setEnabled(false);
            jTextmac.setEnabled(false);
            jTextmarca.setEnabled(false);
            jTextmenoriaram.setEnabled(false);
            jTextmodelo.setEnabled(false);
            jTextmonto.setEnabled(false);
            jTextnumerofactura.setEnabled(false);
            jTextprocesador.setEnabled(false);
            jTextserie.setEnabled(false);
            jTextso.setEnabled(false);
            jTextversion.setEnabled(false);
            
        }else {
            jComboBoxcodigoclase.setEnabled(true);
            jComboBoxcodigoestado.setEnabled(true);
            jComboBoxcodigoproveedores.setEnabled(true);
            jComboBoxcodigoresponsable.setEnabled(true);
            jComboBoxcodigoubicacion.setEnabled(true);
            jTextarquitectura.setEnabled(true);
            jTextcajachica.setEnabled(true);
            jTextcheque.setEnabled(true);
            jTextcodigoempleado.setEnabled(true);
            jTextcodigovogue.setEnabled(true);
            jTextcolor.setEnabled(true);
            jTextdescripcion.setEnabled(true);
            jTextdiscoduro.setEnabled(true);
            jTextFoto.setEnabled(true);
            jTextfecha1.setEnabled(true);
            jTextfechagarantia.setEnabled(true);
            jTextfechainventario.setEnabled(true);
            jTextip.setEnabled(true);
            jTextmac.setEnabled(true);
            jTextmarca.setEnabled(true);
            jTextmenoriaram.setEnabled(true);
            jTextmodelo.setEnabled(true);
            jTextmonto.setEnabled(true);
            jTextnumerofactura.setEnabled(true);
            jTextprocesador.setEnabled(true);
            jTextserie.setEnabled(true);
            jTextso.setEnabled(true);
            jTextversion.setEnabled(true);

        }
   
        
    }    
    
    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Asignaciones dialog = new Asignaciones(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBuscar;
    private javax.swing.JButton bntEliminar;
    private javax.swing.JButton bntGuardar;
    private javax.swing.JButton bntImprimir;
    private javax.swing.JButton bntModificar;
    private javax.swing.JButton bntNuevo;
    private javax.swing.JButton bntRegresar;
    private javax.swing.JButton jButtonFoto;
    private javax.swing.JComboBox jComboBoxcodigoclase;
    private javax.swing.JComboBox jComboBoxcodigoestado;
    private javax.swing.JComboBox jComboBoxcodigoproveedores;
    private javax.swing.JComboBox jComboBoxcodigoresponsable;
    private javax.swing.JComboBox jComboBoxcodigoubicacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFoto;
    private javax.swing.JTextField jTextarquitectura;
    private javax.swing.JTextField jTextcajachica;
    private javax.swing.JTextField jTextcheque;
    private javax.swing.JTextField jTextcodigoactivo;
    private javax.swing.JTextField jTextcodigoempleado;
    private javax.swing.JTextField jTextcodigovogue;
    private javax.swing.JTextField jTextcolor;
    private javax.swing.JTextField jTextdescripcion;
    private javax.swing.JTextField jTextdiscoduro;
    private javax.swing.JTextField jTextfecha1;
    private javax.swing.JTextField jTextfechagarantia;
    private javax.swing.JTextField jTextfechainventario;
    private javax.swing.JTextField jTextip;
    private javax.swing.JTextField jTextmac;
    private javax.swing.JTextField jTextmarca;
    private javax.swing.JTextField jTextmenoriaram;
    private javax.swing.JTextField jTextmodelo;
    private javax.swing.JTextField jTextmonto;
    private javax.swing.JTextField jTextnumerofactura;
    private javax.swing.JTextField jTextprocesador;
    private javax.swing.JTextField jTextserie;
    private javax.swing.JTextField jTextso;
    private javax.swing.JTextField jTextversion;
    private javax.swing.JLabel lblfoto;
    // End of variables declaration//GEN-END:variables
}
