/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package activofijos;

import ClaseConectar.Conectar;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author Jaime Gattorno
 */
public class Buscar extends javax.swing.JDialog {

    DefaultTableModel lModelo;
    String cadena = "";  
    /**
     * Creates new form Buscar
     */
    public Buscar(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        lModelo = new DefaultTableModel();
        lModelo.addColumn("Codigo");
        lModelo.addColumn("Serie");
        lModelo.addColumn("Marca");
        lModelo.addColumn("Nombre Activo");
        lModelo.addColumn("Ubicacion");
        lModelo.addColumn("Responsable");
        lModelo.addColumn("Color");
        lModelo.addColumn("Modelo");
        lModelo.addColumn("Memoria");
        lModelo.addColumn("Disco Duro");
        lModelo.addColumn("Procesador");
        jTableBuscar.setModel(lModelo);
        jTableBuscar.setRowSelectionAllowed(true);
        JTable miJTable = jTableBuscar;
        
        TableColumn tcCodigo = jTableBuscar.getColumn("Codigo");
        TableColumn tcSerie = jTableBuscar.getColumn("Serie");
        TableColumn tcMarca = jTableBuscar.getColumn("Marca");
        TableColumn tcDescripcion = jTableBuscar.getColumn("Nombre Activo");
        TableColumn tcUbicacion = jTableBuscar.getColumn("Ubicacion");
        TableColumn tcNombre = jTableBuscar.getColumn("Responsable");
        TableColumn tcColor= jTableBuscar.getColumn("Color");
        TableColumn tcModelo = jTableBuscar.getColumn("Modelo");
        TableColumn tcMemoria = jTableBuscar.getColumn("Memoria");
        TableColumn tcDiscoDuro = jTableBuscar.getColumn("Disco Duro");
        TableColumn tcProcesador = jTableBuscar.getColumn("Procesador");
        // TableColumn tcResponsable = this.jTableBuscar.getColumn("Responsable");
        
        tcCodigo.setMinWidth(50);
        tcCodigo.setMaxWidth(50);
        tcSerie.setMinWidth(170);        
        tcSerie.setMaxWidth(170);
        tcMarca.setMaxWidth(150);
        tcMarca.setMinWidth(150);
        tcDescripcion.setMinWidth(120);
        tcDescripcion.setMaxWidth(120);
        tcUbicacion.setMinWidth(220);
        tcUbicacion.setMaxWidth(220);
        tcNombre.setMinWidth(120);
        tcNombre.setMaxWidth(120);
        tcColor.setMinWidth(100);
        tcColor.setMaxWidth(100);
        tcModelo.setMinWidth(100);
        tcModelo.setMaxWidth(100);
        tcMemoria.setMinWidth(80);
        tcMemoria.setMaxWidth(80);
        tcDiscoDuro.setMinWidth(80);
        tcDiscoDuro.setMaxWidth(80);
        tcProcesador.setMinWidth(150);
        tcProcesador.setMaxWidth(150);
        
        setEventoMouseClicked(jTableBuscar);  
       
    }
    
    public String getcadena() {
        return cadena;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        txtSerie = new java.awt.TextField();
        bntBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBuscar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextElegido = new javax.swing.JTextField();
        txtNombre = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDescripcion = new java.awt.TextField();
        bntRegresar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setText("Serie");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 48, -1));

        txtSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerieActionPerformed(evt);
            }
        });
        txtSerie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSerieKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSerieKeyTyped(evt);
            }
        });
        getContentPane().add(txtSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 134, -1));

        bntBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/activofijos/Iconos/Buscar32.png"))); // NOI18N
        bntBuscar.setToolTipText("Buscar");
        bntBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(bntBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 40, 40));

        jTableBuscar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Serie", "Marca", "Nombre Activo", "Ubicacion", "Responsable", "Color", "Modelo", "Memoria", "Disco Duro", "Procesador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableBuscarKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTableBuscar);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1340, 440));

        jLabel1.setText("Código");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));
        getContentPane().add(jTextElegido, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 177, -1));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 233, -1));

        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, 20));

        jLabel3.setText("Descripciòn");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        txtDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionActionPerformed(evt);
            }
        });
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyTyped(evt);
            }
        });
        getContentPane().add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 230, -1));

        bntRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/activofijos/Iconos/regresar32.png"))); // NOI18N
        bntRegresar.setToolTipText("Regresar");
        bntRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(bntRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 40, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/activofijos/Imprimir32.png"))); // NOI18N
        jButton1.setText("ImprimirGlobal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerieActionPerformed

    private void txtSerieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerieKeyPressed

        //if (evt.getKeyCode()==13){

            //   JOptionPane.showConfirmDialog(null, "hola");
            //}
    }//GEN-LAST:event_txtSerieKeyPressed

    private void txtSerieKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSerieKeyTyped
        // TODO add your handling code here:

        //if (evt.getKeyChar()==13){

            //   JOptionPane.showConfirmDialog(null, "hola");
            //}
    }//GEN-LAST:event_txtSerieKeyTyped

    private void bntBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntBuscarActionPerformed
        String cSerie = "";
        String cNombre = "";
        String cDescripcion = "";
        cSerie = txtSerie.getText().trim();
        cNombre = txtNombre.getText().trim();
        cDescripcion = txtDescripcion.getText().trim();

        // Vaciar modelo
        try {

            int lFilas = lModelo.getRowCount()-1;
            for (int i = lFilas; i>=0; i--) {

                //for (int i=0;i<lModelo.getRowCount()-1; i++) {
                    lModelo.removeRow(i);
                }

            } catch (Exception e ) {
                JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
            }

        if ( cSerie.length() > 0 || cNombre.length() > 0 || cDescripcion.length() > 0) {
            Conectar nConexion = new Conectar();
            nConexion.conectar();
            Statement st = nConexion.conexion();
            String cSql = "";
            String cWhere = "";
            
            if (cSerie.length() > 0) {
                cWhere = " WHERE ";
                cWhere = cWhere + "A.Serie ILIKE '%" + cSerie + "%' \n" ;
            }
            
            if (cNombre.length() > 0){
                if (cWhere.length() > 0){
                    cWhere = cWhere + " AND R.Nombre ILIKE '%" + cNombre + "%' \n" ;
                }else {
                    cWhere = " WHERE ";
                    cWhere = cWhere + "R.Nombre ILIKE '%" + cNombre + "%' \n" ;
                }
            }
            
            if (cDescripcion.length() > 0){
                if (cWhere.length() > 0){
                    cWhere = cWhere + " AND M.Descripcion ILIKE '%" + cDescripcion + "%' \n" ;
                }else {
                    cWhere = " WHERE ";
                    cWhere = cWhere + " M.Descripcion ILIKE '%" + cDescripcion + "%' \n" ;
                }
            }
            cSql ="SELECT A.codigoActivo\n" +
            "	,A.Serie\n" +
            "	,A.Marca\n" +                    
            "	,M.Descripcion\n" +
            "	,U.Descripcion As descUbicaciones\n" +
            "	,R.Nombre\n" +                       
            "	,A.Color\n" +
            "	,A.Modelo\n" +
            "	,A.Menoriaram\n" +
            "	,A.DiscoDuro\n" +
            "	,A.Procesador\n" +
            "    FROM Activos A\n" +
            "      LEFT JOIN Responsables R ON A.codigoResponsable = R.codigoResponsable \n" +
            "      LEFT JOIN Ubicaciones U ON A.codigoUbicacion = U.codigoUbicacion\n" +
            "      LEFT JOIN Clases M ON A.codigoClase = M.codigoClase\n" +
            cWhere ;

            //JOptionPane.showMessageDialog(null, cSql);
            
            ResultSet rs = nConexion.slqConsulta(st,cSql);

            // Cargar el modelo con los datos
            try {
                // Cargar los datos del ResultSet a la tabla

                int nColumnas = 0;
                nColumnas = this.jTableBuscar.getColumnCount();

                while (rs.next())
                {
                    // Se crea un arreglo que será una de las filas de la tabla.
                    Object [] lFila = new Object[nColumnas]; //Numero de columnas en la tabla

                    // Se crea un ciclo for para cada columna de la tabla
                    for (int i=0; i<nColumnas; i++)
                    lFila[i] = rs.getObject(i+1); //El primer indice del rs es 1 y el arreglo comienza en cero

                    lModelo.addRow(lFila);

                }  } catch (SQLException ex) {
                    Logger.getLogger(Buscar.class.getName()).log(Level.SEVERE, null, ex);

                }
                //this.jTableBuscar;
                nConexion.cerrar(st);
                nConexion.desconectar();
            }
    }//GEN-LAST:event_bntBuscarActionPerformed

    private void jTableBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableBuscarKeyPressed
        // TODO add your handling code here:

        //JOptionPane.showMessageDialog(null, "Hola");
    }//GEN-LAST:event_jTableBuscarKeyPressed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionActionPerformed

    private void txtDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionKeyPressed

    private void txtDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionKeyTyped

    private void bntRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegresarActionPerformed
        // BOTON DE ASIGNACION
         this.dispose();
    }//GEN-LAST:event_bntRegresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String path = "D:\\NetBeansProjects\\Versiones de Java Activos\\ActivosFijos 0.0.0.7\\src\\Reportes\\report2.jasper";
        JasperReport jr = null;
        //jr = (JasperReport) JRLoader.loadObjectFromFile(path);
        
                               
                        
                     
    }//GEN-LAST:event_jButton1ActionPerformed

     private void setEventoMouseClicked(JTable jTableBuscar) 
    {
        jTableBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
    
        @Override
        public void mouseClicked(MouseEvent e) {
            miJTableMouseClicked(e);
        }
        }
        );
    }
    private void miJTableMouseClicked(java.awt.event.MouseEvent evt ){
        
     //   JOptionPane.showMessageDialog(null,  "Imposible conectarse al servidor de datos " , "Error de mouse", JOptionPane.INFORMATION_MESSAGE );
        int row = jTableBuscar.rowAtPoint(evt.getPoint());
        if (row >= 0 && jTableBuscar.isEnabled()){
            cadena = jTableBuscar.getValueAt(row, 0).toString();
            jTextElegido.setText(cadena);
        }
       // JOptionPane.showMessageDialog(null, cadena);
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntBuscar;
    private javax.swing.JButton bntRegresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableBuscar;
    private javax.swing.JTextField jTextElegido;
    private java.awt.Label label1;
    private java.awt.TextField txtDescripcion;
    private java.awt.TextField txtNombre;
    private java.awt.TextField txtSerie;
    // End of variables declaration//GEN-END:variables

    public String getjTextElegido(){
        return jTextElegido.getText().trim();
    }
}
