/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package activofijos;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import ClaseConectar.Conectar;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Juan
 */
public class EstadoActivo extends javax.swing.JDialog {
       DefaultTableModel modelo;
       int con = 0;
    
       public EstadoActivo() {
       initComponents();
        
       modelo = new DefaultTableModel ();
       modelo. addColumn ("No.");
       modelo. addColumn ("Descripcion");
       this.jTable1.setModel(modelo);
        
    }
    /**
     * Creates new form NewJDialog
     */
    public EstadoActivo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bntGuardar = new javax.swing.JButton();
        bntEliminar = new javax.swing.JButton();
        bntRegresar = new javax.swing.JButton();
        bntNuevo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextDescripcion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextEstados = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(475, 460));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bntGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/activofijos/Iconos/Guardar32.png"))); // NOI18N
        bntGuardar.setToolTipText("guardar");
        bntGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(bntGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 40, 40));

        bntEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/activofijos/Iconos/Borrar32.png"))); // NOI18N
        bntEliminar.setToolTipText("Eliminar");
        getContentPane().add(bntEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 40, 40));

        bntRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/activofijos/Iconos/regresar32.png"))); // NOI18N
        bntRegresar.setToolTipText("Regresar");
        bntRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(bntRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 40, 40));

        bntNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/activofijos/Iconos/Nuevo32.png"))); // NOI18N
        bntNuevo.setToolTipText("Nuevo");
        bntNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(bntNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 40, 40));

        jLabel3.setText("Descripcion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        getContentPane().add(jTextDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 170, -1));

        jLabel2.setText("No.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        getContentPane().add(jTextEstados, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 100, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ESTADO DEL ACTIVO");
        jLabel1.setMaximumSize(new java.awt.Dimension(50, 24));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 450, 270));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bntGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntGuardarActionPerformed
        // TODO add your handling code here:
        String cCodigoActivo = "0";
        Integer.parseInt(cCodigoActivo);
        String cDescripcion = "";
        String cMarca = "";
        String cModelo = "";
        String cSerie = "";
        String cCodigoUbicacion = "0";
        Integer.parseInt(cCodigoUbicacion);
        String cCodigoEstado = "0";
        Integer.parseInt(cCodigoEstado);
        String cCodigoProveedor = "";
        String dFecha = "";
        Integer nNumerofactura = 0;
        double nMonto = 0.0;
        Integer nCheque = 0;
        String cCodigoClase = "0";
        Integer.parseInt(cCodigoClase);
        String cCodigoResponsable = "0";
        Integer.parseInt(cCodigoResponsable);
        String dFechainventario = "";
        String cCodigovogue = "0";
        Integer.parseInt(cCodigovogue);
        Integer cCodigoempleado = 0;
        String dFechagarantia = "";
        String cDiscoduro = "";
        String cMenoriaram = "";
        String cIp = "";
        String cMac = "";
        String cProcesador = "";
        String cSo = "";
        String cVersion = "";
        String cArquitectura = "";
        String cColor = "";
        String cCajachica = "";
        String cTempo = "";
/**
        cCodigoActivo = jTextcodigoactivo.getText();
        cDescripcion = jTextdescripcion.getText();
        cMarca = jTextmarca.getText();
        cModelo = jTextmodelo.getText();
        cSerie = jTextserie.getText();
        cCodigoUbicacion =  jComboBoxcodigoubicacion.getSelectedItem().toString().substring(0, 7);
        cCodigoEstado = jComboBoxcodigoestado.getSelectedItem().toString().substring(0,7);
        cCodigoProveedor =  jComboBoxcodigoproveedores.getSelectedItem().toString().substring(0, 7);
*/
   /**     // Validar Fecha
        if (jTextfecha.getText().trim().length() == 0){
            dFecha = "1900/01/01";
        } else {
            dFecha = jTextfecha.getText();
        }
        // Validar Numero de factura
        if (jTextnumerofactura.getText().trim().length() == 0) {
            nNumerofactura = 0;
        } else {
            nNumerofactura = Integer.parseInt(jTextnumerofactura.getText());
        }
        // Validar Monto
        if (jTextmonto.getText().trim().length() == 0){
            nMonto = 0;
        } else {
            nMonto = Double.parseDouble(jTextmonto.getText());
        }
        // Validar Cheque
        if (jTextcheque.getText().trim().length() == 0) {
            nCheque = 0;
        } else {
            nCheque = Integer.parseInt(jTextcheque.getText());
        }

        cCodigoClase = jComboBoxcodigoclase.getSelectedItem().toString().substring(0,7);;
        cCodigoResponsable = jComboBoxcodigoresponsable.getSelectedItem().toString().substring(0, 7);

        // Validar Fecha inventario
        if (jTextfechainventario.getText().trim().length() == 0){
            dFechainventario = "1900/01/01";
        } else {
            dFechainventario = jTextfechainventario.getText();
        }

        cCodigovogue = jTextcodigovogue.getText();

        // Validar Codigo Empleado
        if (jTextcodigoempleado.getText().trim().length() == 0) {
            cCodigoempleado = 0;
        } else {
            cCodigoempleado = Integer.parseInt(jTextcodigoempleado.getText());
        }

        // Validar Fecha Garantia
        if (jTextfechagarantia.getText().trim().length() == 0){
            dFechagarantia = "1900/01/01";
        } else {
            dFechagarantia = jTextfechagarantia.getText();
        }

        cDiscoduro = jTextdiscoduro.getText();
        cMenoriaram = jTextmenoriaram.getText();
        cIp = jTextip.getText();
        cMac = jTextmac.getText();
        cProcesador = jTextprocesador.getText();
        cSo = jTextso.getText();
        cVersion = jTextversion.getText();
        cArquitectura = jTextarquitectura.getText();
        cColor = jTextcolor.getText();
        cCajachica = jTextcajachica.getText();
*/
        // Codigo para conectarse y grabar en la base de datos

        Conectar nConexion = new Conectar();
        nConexion.conectar();
        Statement st = nConexion.conexion();

        String cSql;
        cSql = "DELETE FROM activos WHERE codigoactivo = '" + cCodigoActivo + "';" +
        "INSERT INTO activos"+
        "(codigoactivo, descripcion, marca, modelo, serie, codigoubicacion, codigoestado, codigoproveedor,"
        + " fecha, numerofactura, monto, cheque, codigoclase, codigoresponsable, fechainventario, codigovogue,"
        + " codigoempleado, fechagarantia, discoduro, menoriaram, ip, mac, procesador, so,version,"
        + " arquitectura, color, cajachica)" +
        " SELECT " + cCodigoActivo + "" +
        "   ,'" + cDescripcion + "'" +
        "   ,'" + cMarca + "'" +
        "   ,'" + cModelo + "'" +
        "   ,'" + cSerie + "'" +
        "   , " + cCodigoUbicacion + "" +
        "   , " + cCodigoEstado + "" +
        "   , " + cCodigoProveedor + "" +
        "   , '" + dFecha + "'" +
        "   , " + nNumerofactura +
        "   , " + nMonto +
        "   , " + nCheque +
        "   , " + cCodigoClase + "" +
        "   , " + cCodigoResponsable + "" +
        "   ,'" + dFechainventario + "'" +
        "   , " + cCodigovogue + "" +
        "   , " + cCodigoempleado + "" +
        "   ,'" + dFechagarantia + "'" +
        "   ,'" + cDiscoduro + "'" +
        "   ,'" + cMenoriaram + "'" +
        "   ,'" + cIp + "'" +
        "   ,'" + cMac + "'" +
        "   ,'" + cProcesador + "'" +
        "   ,'" + cSo + "'" +
        "   ,'" + cVersion + "'" +
        "   ,'" + cArquitectura + "'" +
        "   ,'" + cColor + "'" +
        "   ,'" + cCajachica + "'" +
        " WHERE NOT EXISTS " +
        "    ( SELECT * FROM activos " +
        "         WHERE codigoactivo = '" + cCodigoActivo + "' )";

        nConexion.slqActualiza(st, cSql);
        nConexion.cerrar(st);
        nConexion.desconectar();
        JOptionPane.showMessageDialog(null, "Los datos se guardaron con éxito");

    }//GEN-LAST:event_bntGuardarActionPerformed

    private void bntRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntRegresarActionPerformed
        // BOTON DE ASIGNACION
        this.dispose();
    }//GEN-LAST:event_bntRegresarActionPerformed

    private void bntNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntNuevoActionPerformed
       /**
        jTextarquitectura.setText("");
        jTextcajachica.setText("");
        jTextcheque.setText("");
        jTextcodigoactivo.setText("");
        jTextcodigoempleado.setText("");
        jTextcodigovogue.setText("");
        jTextcolor.setText("");
        jTextdescripcion.setText("");
        jTextdiscoduro.setText("");
        jTextfecha.setText("");
        jTextfecha1.setText("");
        jTextfechagarantia.setText("");
        jTextfechainventario.setText("");
        jTextip.setText("");
        jTextmac.setText("");
        jTextmarca.setText("");
        jTextmenoriaram.setText("");
        jTextmodelo.setText("");
        jTextmonto.setText("");
        jTextnumerofactura.setText("");
        jTextprocesador.setText("");
        jTextserie.setText("");
        jTextso.setText("");
        jTextversion.setText("");

        jComboBoxcodigoubicacionIniciar("");
        jComboBoxcodigoestadoIniciar("");
        jComboBoxcodigoproveedoresIniciar("");
        jComboBoxcodigoclaseIniciar("");
        jComboBoxcodigousuarioIniciar("");
        establecerAcceso(1);

        try {
            jTextcodigoactivo.setText(devolverCodigo().toString());
        } catch (SQLException ex) {
            Logger.getLogger(Asignaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextcodigovogue.setFocusable(true);
        * /

    }//GEN-LAST:event_bntNuevoActionPerformed

    /**
     * @param args the command line arguments
     * /
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EstadoActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EstadoActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EstadoActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EstadoActivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EstadoActivo dialog = new EstadoActivo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEliminar;
    private javax.swing.JButton bntGuardar;
    private javax.swing.JButton bntNuevo;
    private javax.swing.JButton bntRegresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextDescripcion;
    private javax.swing.JTextField jTextEstados;
    // End of variables declaration//GEN-END:variables
}
